services:
  ignite:
    image: apacheignite/ignite:3.1.0
    container_name: energy-ignite
    command:
      --node-name energy-ignite
    ports:
      - "10300:10300"
      - "10800:10800"
    restart: unless-stopped
  kafka:
    image: apache/kafka:latest
    container_name: energy-kafka
    ports:
      - "9092:9092"
    restart: unless-stopped

